---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  replicas: {{.Values.ingressController.replicas}}
  selector:
    matchLabels:
        k8s-app: {{ .Release.Name }}-lb
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}-lb
    spec:
      serviceAccountName: {{ .Release.Name }}-serviceaccount
      containers:
        - name: {{ .Release.Name }}-controller
          image: {{.Values.ingressController.image}}:{{.Values.ingressController.version}}
          args:
             - /nginx-ingress-controller
             {{- if .Values.defaultBackend.namespace }}
             - --default-backend-service={{ .Values.defaultBackend.namespace }}/{{ .Release.Name }}-default-http-backend
             {{- else }}
             - --default-backend-service={{ .Release.Namespace }}/{{ .Release.Name }}-default-http-backend
             {{- end}}
             - --default-ssl-certificate=$(POD_NAMESPACE)/tls-certificate
             {{- if .Values.ingressController.namespace }}
             - --watch-namespace={{ .Values.ingressController.namespace }}
             {{- end }}
             {{- if .Values.ingressController.class }}
             - --ingress-class={{ .Values.ingressController.class }}
             {{- end }}
             {{- if .Values.tcpServices.enabled }}
             - --tcp-services-configmap=$(POD_NAMESPACE)/{{ .Release.Name }}-tcpservices-configmap
             {{- end }}
             - --configmap=$(POD_NAMESPACE)/{{ .Release.Name }}-load-balancer-conf
          env:
             - name: POD_NAME
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.name
             - name: POD_NAMESPACE
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.namespace
          ports:
          {{- range .Values.ingressController.ports}}
          - name: {{ .name }}
            containerPort: {{ .number }}
          {{- end }}
          {{- if .Values.tcpServices.enabled }}
          {{- range .Values.tcpServices.mappings }}
          - name: {{ .name }}
            containerPort: {{ .number }}
          {{- end }}
          {{- end }}
